name: IPA Build

on:
  # Runs on push to any of the below branches
  push:
    branches:
      - main

  # Runs on pull request events that target one of the below branches
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab of the repository
  workflow_dispatch:

env:
  # https://flet.dev/docs/publish#versioning
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0

  # Python version to use
  PYTHON_VERSION: 3.12.8

  # flet-cli version to install for `flet build`
  FLET_CLI_VERSION: 0.28.2

  # Ensures Python uses UTF-8 encoding by default
  PYTHONUTF8: 1

  # Disables rich text formatting in Flet CLI output
  FLET_CLI_NO_RICH_OUTPUT: 1

  # Disables progress bars when using UV
  UV_NO_PROGRESS: 1

  # Directorio del ejemplo que contiene el pyproject.toml
  EXAMPLE_DIR: examples/flet_pro_image_editor_example


jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install flet-cli ${{ env.FLET_CLI_VERSION }}
      run: |
        python -m pip install --upgrade pip
        pip install flet-cli==$FLET_CLI_VERSION

    - name: Fix pyproject.toml paths for macOS
      run: |
        cd $EXAMPLE_DIR
        # Mostrar el contenido original para depuración
        cat pyproject.toml
        # Crear un archivo temporal con las rutas corregidas
        cat pyproject.toml | sed 's/\.\.\\\.\./\.\.\/\.\./' > pyproject_fixed.toml
        # Reemplazar el archivo original con el corregido
        mv pyproject_fixed.toml pyproject.toml
        # Mostrar el contenido modificado para verificar
        cat pyproject.toml

    - name: Install package in development mode
      run: |
        pip install -e .

    - name: Flet Build IPA
      run: |
        cd $EXAMPLE_DIR
        flet build ipa --verbose --build-number=$BUILD_NUMBER --build-version=$BUILD_VERSION 

    - name: Upload IPA Artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: ipa-build-artifact
        path: ${{ env.EXAMPLE_DIR }}/build/ipa
        if-no-files-found: error
        overwrite: false